[programs.devnet]
myepicproject = "o4RD8aU7TuiN7mEFJLhbCudeVFmt7Mpo2VWKB7zS8oi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/cryptopragmatic/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
